### ISSUE TITLE
Option "Rotate" "left" crashes xserver

### ISSUE THREAD

**Issue by jochenjagers** [grate-driver/xf86-video-opentegra#27]
Hello,

i tried to rotate the output of xserver on my Tegra20.
But as soon as i add the option to the xorg.conf the server crashes on startup.

Log and config are attached:
[Xorg.0.log](https://github.com/grate-driver/xf86-video-opentegra/files/1359481/Xorg.0.log)
[xorg.conf.txt](https://github.com/grate-driver/xf86-video-opentegra/files/1359486/xorg.conf.txt)

gdb showed the following stacktrace:
[stacktrace.txt](https://github.com/grate-driver/xf86-video-opentegra/files/1359498/stacktrace.txt)

**Comment by digetx** [comment]
Hello jochenjagers,

I've opened https://github.com/grate-driver/xf86-video-opentegra/pull/28 that fixes this issue. Thank you for the report! Rotation works now, but maybe in not the most optimal way.
