### ISSUE TITLE
 AddScreen/ScreenInit failed for driver

### ISSUE THREAD

**Issue by bbnote** [grate-driver/xf86-video-opentegra#48]
Hello,

since the commits from Jan 11, starting up X giving me: AddScreen/ScreenInit failed for driver 0.

Rolling back to 142f28acc6a0feeb039346d75dd3319df7991de7 solved the issue. 

Log files:

[X11_Output.log](https://github.com/grate-driver/xf86-video-opentegra/files/2755755/X11_Output.log)

[Xorg.log](https://github.com/grate-driver/xf86-video-opentegra/files/2755756/Xorg.log)

[xorg_conf.txt](https://github.com/grate-driver/xf86-video-opentegra/files/2755762/xorg_conf.txt)

**Comment by digetx** [comment]
@bbnote, thank you very much for the report. Could you please post Xorg.log of the working Xorg? I suspect that Xv initialization is what fails, previously we just ignored the error.

```
[   330.419] (**) opentegra(0): Depth 16, (--) framebuffer bpp 16
[   330.419] (==) opentegra(0): RGB weight 565
```

16bit framebuffer is also interesting :) Do you know if LCD panel of your device supports generic RGBX 32bit format? 16bit definitely not getting much testing, maybe we should do something better about format selection in the driver.

**Comment by digetx** [comment]
@bbnote Pushed https://github.com/grate-driver/xf86-video-opentegra/commit/55d50dc7f6d7c0139bc9169c0fe254025f6f15d6 and some other patches that should help with your problem, please give it a try and post the updated Xorg.log

**Comment by bbnote** [comment]
Hi @digetx,

thank you very much, 55d50dc7f6d7c0139bc9169c0fe254025f6f15d6 solved the problem. Xserver is working again.

[XorgUpdated.log](https://github.com/grate-driver/xf86-video-opentegra/files/2758594/XorgUpdated.log)

**Comment by digetx** [comment]
@bbnote, Awesome! Recent commit https://github.com/grate-driver/xf86-video-opentegra/commit/57a430f361c5059e3df65b008705199d483e5709 should fix Xv initialization for you, could you please give it a try?

Could you please clarify whether 16bit display format is what you're setting manually or it is getting autoselected?

**Comment by bbnote** [comment]
@digetx, everything is working great now. Thanks :)

The used lcd panel indeed just uses 16bit, which is set by "DefaultDepth 16". But I found out that using 24 bit is working as well.

**Comment by digetx** [comment]
@bbnote Nice, I also added 16bit support to https://github.com/grate-driver/libvdpau-tegra/commit/30bb8af9926ed6496c5bd95e713519e25b1aee13, so seems there is full set now. Please let us know if you'll spot any other problems.
