### ISSUE TITLE
libturbojpeg dependency instead of libturbojpeg0

### ISSUE THREAD

**Issue by dpavlin** [grate-driver/xf86-video-opentegra#53]
Can you please change debian/control for xserver-xorg-video-opentegra to depend on libturbojpeg0 instead of libturbojpeg ?

Source package already depends on libturbojpeg0-dev and libturbojpeg doesn't exists on Debian, so rebuild packages won't install without manually changing debian/control and rebuilding.

**Comment by digetx** [comment]
Hello, @dpavlin! I add libturbojpeg0 as alternative dependency here https://github.com/grate-driver/xf86-video-opentegra/commit/2e1c8c909dd7e102483243c09028042eaafcc1a9, please let me know if it works for you.

**Comment by digetx** [comment]
@dpavlin, is the problem resolved now?

**Comment by dpavlin** [comment]
It is, thank you. I have trouble keeping my old tegra thinkpad tablet alive
enough to make recompile, sorry for delay.

**Comment by digetx** [comment]
No problems, indeed it takes quite a lot of effort to maintain tegra devices, although the same applies any ARM-powered device due to not-exellent upstream support from the vendors. Please let us know if you'll have any other requests! I'm closing this bug since it is resolved now.
