### ISSUE TITLE
freedesktop.org gitlab access, latest mesa for opentegra

### ISSUE THREAD

**Issue by emulti** [grate-driver/xf86-video-opentegra#55]
Hello,

How would I go about obtaining read access to the latest mesa in https://gitlab.freedesktop.org/kusma/mesa/tree/master  ?

I want to try and make a PKGBUILD for Arch linux/AC100 to further test on an AC100.

I tried cloning https://gitlab.freedesktop.org/kusma/mesa/mesa-master.git using Gitlab username and a 'personal access token' but receive 'project you are looking for cannot be found'.

**Comment by emulti** [comment]
I think so, probably for AC100 I need the grate branch
Would that be ..../mesa-grate.git ?

**Comment by digetx** [comment]
@emulti 

```
# git clone https://gitlab.freedesktop.org/kusma/mesa.git
# cd mesa
# git checkout grate
```

**Comment by emulti** [comment]
Thanks!
