### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by ollieparanoid** [grate-driver/xf86-video-opentegra#63]
@okias, can you explain in the README why the git repo lives here and not on freedesktop.org?

> The master development code repository can be found at:
>
>        git://anongit.freedesktop.org/git/xorg/driver/xf86-video-tegra
>
>        http://cgit.freedesktop.org/xorg/driver/xf86-video-tegra

These links are dead.

Also since you are upstream, how about tagging releases? :slightly_smiling_face:

**Comment by okias** [comment]
@digetx ACK?

**Comment by digetx** [comment]
Yes, thank you for yours help!

**Comment by okias** [comment]
> can you explain in the README why the git repo lives here and not on freedesktop.org?

TBH, no idea. But I did updated README to reflect current urls.

**Comment by digetx** [comment]
Initially this was a fork with extra experimental features and the plan was to upstream the features once they are ready, but then Xorg became considered as a dead project, so we never got around to merging anything to upstream.

**Comment by ollieparanoid** [comment]
Thanks for the explanation and for updating the README!
