### ISSUE TITLE
Tearing

### ISSUE THREAD

**Issue by KaiJan57** [grate-driver/xf86-video-opentegra#64]
Is there a way to get around screen tearing?

**Comment by digetx** [comment]
Do you have compositing enabled? For xfce it requires to use compositor like compton, IIRC.

**Comment by KaiJan57** [comment]
No... I'll try later and see if that works. I'm using mate-desktop BTW.

**Comment by digetx** [comment]
In MATE you may need to enable compositing somewhere in settings, it's probably disabled by default for xrender.

**Comment by KaiJan57** [comment]
Compositor doesn't seem to help (tried picom)

**Comment by digetx** [comment]
Then it's probably not fixable for today. The VDPAU output uses display overlay, so at least video should be without tearing.

**Comment by KaiJan57** [comment]
Okay, thank you very much!
